services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - chat-net

  server:
    build:
      context: .
      dockerfile: cmd/server/server.Dockerfile
    depends_on:
      - nats
    networks:
      - chat-net
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats:4222

networks:
  chat-net:
    driver: bridge
